default: &default
  host: localhost
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 10000
  database: steemhunt
  username: steemhunt

docker:
 <<: *default
 host: <%= ENV['DB_HOST'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  password: <%= ENV["DB_PASSWORD"] %>
  pool: 50